"""init

Revision ID: 0b00a2afdddd
Revises: 
Create Date: 2022-03-08 17:32:44.763931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b00a2afdddd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gid", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("publication_date", sa.DateTime(), nullable=True),
        sa.Column("number_of_pages", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("preview_link", sa.String(length=200), nullable=True),
        sa.Column("isbn_10", sa.String(length=10), nullable=True),
        sa.Column("isbn_13", sa.String(length=13), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gid"),
        sa.UniqueConstraint("isbn_10"),
        sa.UniqueConstraint("isbn_13"),
    )
    op.create_table(
        "book_author",
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "book_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_author")
    op.drop_table("book")
    op.drop_table("author")
    # ### end Alembic commands ###
